# Generated by Django 6.1 on 2026-09-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["position"]},
        ),
    ]
